### ISSUE TITLE
Use a different graphing/charting utility

### ISSUE THREAD

**Issue by ghost** [bennacer860/benford_s_law#3]
As for the making of the chart, you might want to use something like [ascii_charts](https://github.com/benlund/ascii_charts) to produce really nice looking graphs or charts. Here's an example. Say we use that ascii_charts gem. We take the hash that your script already gives us, and convert it into an array. Then we use the ascii_charts gem.

``` ruby
array = []
{"1"=>56.86, "2"=>20.68, "3"=>8.15, "4"=>5.37, "5"=>2.98, "6"=>2.19, "7"=>0.99, "8"=>1.19, "9"=>1.59}.each { |k,v| array << [k,v] }
puts AsciiCharts::Cartesian.new(array).draw
```

And get a really nice looking result of.

```
60.0|                  
55.0|*                 
50.0|                  
45.0|                  
40.0|                  
35.0|                  
30.0|                  
25.0|                  
20.0|  *               
15.0|                  
10.0|    *             
 5.0|      * *         
 0.0+----------*-*-*-*-
     1 2 3 4 5 6 7 8 9
```

Or maybe even [experiment](http://effectif.com/ruby/manor/data-visualisation-with-ruby) with [Google Charts](https://developers.google.com/chart/)?

**Comment by bennacer860** [comment]
This is an awesome idea, i will try it and see. I am sure AsciiCharts::Cartesian is better to visualize the data than the custom charts i have created :).

**Comment by ghost** [comment]
OK, great. I'll try to implement that feature and let you know how it turns out.

**Comment by bennacer860** [comment]
ok this is really cool, i will work tonight on: 
-Computing the mean absolute deviation to score the result
-Create a dataset with fibonacci serie and test it

**Comment by ghost** [comment]
That would be nice. Before you do that, could you just wait before I play around with the code a bit, and add documentation to it and make it feel more like a library? It will only couple couple of minutes, you'll see what I mean.

**Comment by bennacer860** [comment]
ok,take your time, i will work on it in a 5 hours :)

**Comment by ghost** [comment]
Oh, okay.

**Comment by bennacer860** [comment]
can you make a pull request please?

**Comment by ghost** [comment]
Will do, once I'm finished. _Nearly done..._

**Comment by bennacer860** [comment]
cool
